"""Generate the TypeScript wire contract without starting the API or calling models."""
import argparse
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
os.environ["APP_ENV"] = "test"
os.environ["DATABASE_URL"] = "sqlite://"


def ts(schema: dict) -> str:
    if "$ref" in schema:
        return f'ApiSchemas[{json.dumps(schema["$ref"].split("/")[-1])}]'
    for keyword, separator in (("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")):
        if keyword in schema:
            return "(" + separator.join(ts(item) for item in schema[keyword]) + ")"
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    kind = schema.get("type")
    if kind == "array":
        return f"Array<{ts(schema.get('items', {}))}>"
    if kind == "object" or "properties" in schema:
        fields = [f'{json.dumps(name)}{"" if name in schema.get("required", []) else "?"}: {ts(value)};'
                  for name, value in schema.get("properties", {}).items()]
        additional = schema.get("additionalProperties")
        if additional is True or isinstance(additional, dict):
            fields.append(f"[key: string]: {ts(additional) if isinstance(additional, dict) else 'unknown'};")
        return "{ " + " ".join(fields) + " }" if fields else "Record<string, unknown>"
    return {"string": "string", "integer": "number", "number": "number",
            "boolean": "boolean", "null": "null"}.get(kind, "unknown")


def main() -> None:
    from app.main import app

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schemas = app.openapi()["components"]["schemas"]
    content = "// Generated by backend/scripts/export_api_types.py; do not edit.\n"
    content += "export interface ApiSchemas {\n"
    content += "\n".join(f"  {json.dumps(name)}: {ts(schema)};"
                         for name, schema in sorted(schemas.items()))
    content += "\n}\n"
    target = ROOT.parent / "frontend/src/lib/api-schema.ts"
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != content:
            raise SystemExit("API schema changed. Run python scripts/export_api_types.py and typecheck.")
        print("API schema is current.")
    else:
        target.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
