"""campaign run state for stepped execution

Revision ID: 2f7c2f4d9817
Revises: c40a12d9e503
Create Date: 2026-09-23 15:33:48.557247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f7c2f4d9817'
down_revision: Union[str, Sequence[str], None] = 'c40a12d9e503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaignrunstate',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('brief', sa.JSON(), nullable=True),
    sa.Column('accepted', sa.JSON(), nullable=True),
    sa.Column('outcomes', sa.JSON(), nullable=True),
    sa.Column('intelligence', sa.JSON(), nullable=True),
    sa.Column('contract', sa.JSON(), nullable=True),
    sa.Column('next_position', sa.Integer(), nullable=False),
    sa.Column('total_positions', sa.Integer(), nullable=False),
    sa.Column('abort_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['campaignexecution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaignrunstate_execution_id'), 'campaignrunstate', ['execution_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaignrunstate_execution_id'), table_name='campaignrunstate')
    op.drop_table('campaignrunstate')
    # ### end Alembic commands ###
