"""initial schema

Revision ID: c5fd057c72cb
Revises: 
Create Date: 2026-08-02 03:25:51.169120

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c5fd057c72cb'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_market', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('goals', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledgedocument',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sa.Enum('MARKDOWN', 'PLAIN_TEXT', 'WEBSITE', name='knowledgesourcetype'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersettings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('brand_voice', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_ai_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaignexecution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='executionstatus'), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaignexecution_campaign_id'), 'campaignexecution', ['campaign_id'], unique=False)
    op.create_table('agentexecution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_execution_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='executionstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_execution_id'], ['campaignexecution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agentexecution_agent_id'), 'agentexecution', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agentexecution_campaign_execution_id'), 'agentexecution', ['campaign_execution_id'], unique=False)
    op.create_table('executionlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_execution_id', sa.Uuid(), nullable=True),
    sa.Column('agent_execution_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', name='loglevel'), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agentexecution.id'], ),
    sa.ForeignKeyConstraint(['campaign_execution_id'], ['campaignexecution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executionlog_agent_execution_id'), 'executionlog', ['agent_execution_id'], unique=False)
    op.create_index(op.f('ix_executionlog_campaign_execution_id'), 'executionlog', ['campaign_execution_id'], unique=False)
    op.create_table('generatedasset',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_execution_id', sa.Uuid(), nullable=False),
    sa.Column('agent_execution_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.Enum('EMAIL', 'SOCIAL_POST', 'AD', 'VIDEO_SCRIPT', 'CREATIVE_PROMPT', name='assettype'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('asset_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agentexecution.id'], ),
    sa.ForeignKeyConstraint(['campaign_execution_id'], ['campaignexecution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generatedasset_agent_execution_id'), 'generatedasset', ['agent_execution_id'], unique=False)
    op.create_index(op.f('ix_generatedasset_campaign_execution_id'), 'generatedasset', ['campaign_execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generatedasset_campaign_execution_id'), table_name='generatedasset')
    op.drop_index(op.f('ix_generatedasset_agent_execution_id'), table_name='generatedasset')
    op.drop_table('generatedasset')
    op.drop_index(op.f('ix_executionlog_campaign_execution_id'), table_name='executionlog')
    op.drop_index(op.f('ix_executionlog_agent_execution_id'), table_name='executionlog')
    op.drop_table('executionlog')
    op.drop_index(op.f('ix_agentexecution_campaign_execution_id'), table_name='agentexecution')
    op.drop_index(op.f('ix_agentexecution_agent_id'), table_name='agentexecution')
    op.drop_table('agentexecution')
    op.drop_index(op.f('ix_campaignexecution_campaign_id'), table_name='campaignexecution')
    op.drop_table('campaignexecution')
    op.drop_table('usersettings')
    op.drop_table('knowledgedocument')
    op.drop_table('campaign')
    # ### end Alembic commands ###
